### ISSUE TITLE
Hwloc/../deps/build.log is installed without user write permission.

### ISSUE THREAD

**Issue by stefan911** [JuliaParallel/Hwloc.jl#20]
(v1.0) pkg> build Hwloc
   Building Homebrew → `~/.julia/packages/Homebrew/s09IX/deps/build.log`
   Building Hwloc ───→ `~/.julia/packages/Hwloc/aHXIz/deps/build.log`
   ERROR: SystemError: opening file /Users/stefan/.julia/packages/Hwloc/aHXIz/deps/build.log:      Permission denied`

   Oban:deps stefan$ chmod +w build.log

**Comment by mbauman** [comment]
This should have been fixed by #19 — this just requires a new release.

**Comment by eschnett** [comment]
@mbauman Is the release process still the same as it used to be, i.e. simply tagging a Github release after updating the version number?

**Comment by mbauman** [comment]
No, you'll want to use the new Registrator.  Details here: https://github.com/JuliaRegistries/Registrator.jl#how-to-use

**Comment by eschnett** [comment]
@JuliaRegistrator register()

**Comment by eschnett** [comment]
@JuliaRegistrator register()

**Comment by eschnett** [comment]
Resolved in release 1.0.1.
